name: Build and deploy in QA

on:
  push:
    branches:    
      - master
      
env:
  applicationfolder: 'src/blank-csharp'
  AWS_REGION: us-east-1
  AWS_S3_BUCKET: git-action-ci-cd-build-qa

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-18.04
    environment: QA
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Dot net dependencies and AWS CLI
        working-directory: './src/blank-csharp'
        run: |
          dotnet restore
          dotnet tool install -g Amazon.Lambda.Tools
      
      - name: Build
        working-directory: './src/blank-csharp'
        run: dotnet build -c debug --no-restore
        
      - name: Test
        working-directory: './src/blank-csharp'
        run: dotnet test --no-restore --verbosity normal

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{env.AWS_REGION}}
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY_ID }}


#       - name: chmod
#         run: chmod -R +x ./.github

      - name: Install zip
        uses: montudor/action-zip@v1
        
      - name: Create Zip File
        run: zip -r blank-csharp.zip ./src

      - name: Upload to S3
        run: aws s3 cp *.zip s3://${{ env.AWS_S3_BUCKET }}/
    
  deploy:
      needs: build
      runs-on: ubuntu-18.04
      environment: QA
      permissions:
        id-token: write
        contents: read
      steps:      
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-region: ${{env.AWS_REGION}}
            aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY_ID }}
      - run: aws lambda update-function-code --function-name git-test-function-QA --s3-bucket ${{ env.AWS_S3_BUCKET }} --s3-key blank-csharp.zip

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Release lambda function version
        run: aws lambda publish-version --function-name git-test-function-QA --description ${{ github.run_id }}
