name: Build and Deploy

on:
  push:
    branches:    
      - Dev
# on:
#     workflow_dispatch: {}

env:
  applicationfolder: './artifacts'
  AWS_REGION: us-east-1
  AWS_S3_BUCKET: git-action-ci-cd-build

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Dot net dependencies and AWS CLI
        working-directory: './src/blank-csharp'
        run: |
          dotnet restore
          dotnet tool install -g Amazon.Lambda.Tools
      
      - name: Build
        working-directory: './src/blank-csharp'
        run: dotnet build -c debug --no-restore

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{env.AWS_REGION}}
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY_ID }}

#       - name: chmod
#         run: chmod -R +x ./.github

      - name: Make artifact directory
        run: mkdir -p ./artifacts/${{ github.repository }}

      - name: Create Zip File
        uses: montudor/action-zip@v1
        with:
          args: zip -r ./artifacts/${{ github.repository }}/${{ github.sha }}.zip ./src

      - name: Upload Artifact to s3
        working-directory: ${{ env.applicationfolder }}/target
        run: aws s3 cp ./artifacts/${{ github.repository }}/${{ github.sha }}.zip s3://${{ env.AWS_S3_BUCKET }}/
#       - name: Install zip
#         uses: montudor/action-zip@v1

#       - name: Zip output
#         run: zip -qq -r helloworld.zip . -i bin/release/netcoreapp3.1
            
#       - name: Upload to S3
#         run: aws s3 cp *.zip s3://${{ env.AWS_S3_BUCKET }}/

  deploy:
    needs: build
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-region: ${{env.AWS_REGION}}
#           role-to-assume: arn:aws:iam::967774776559:role/github-action-access-role
#           role-session-name: development
#           aws-s3-bucket: ${{ env.AWS_S3_BUCKET }}
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY_ID }}
    - run: aws lambda update-function-code --function-name git-test-function --s3-bucket ${{ env.AWS_S3_BUCKET }}

    - name: Sleep for 5 seconds
      run: sleep 5s
      shell: bash

    - name: Release lambda function version
      run: aws lambda publish-version --function-name git-test-function --description ${{ github.run_id }}
